### ISSUE TITLE
Network Logs Not Captured for KMP API Calls

### ISSUE THREAD

**Issue by DaiseiTanaka** [DebugSwift/DebugSwift#117]
## What we want to do
- We would like to obtain the network logs of APIs called via `KMP`.

## Current situation and problem
- We are unable to obtain the logs of the APIs called via KMP.
- With `CocoaDebug`, we can obtain the logs by default.
- We can obtain the network logs from normal API calls.
- KMP uses [Ktor](https://ktor.io/) to obtain logs.

**Comment by heitara** [comment]
Hello @DaiseiTanaka!

Could you please create a basic KMP project that reproduces the problem with DebugSwift library. This will speed up the development of the fix.

Thank you!

@MaatheusGois I believe [this](https://github.com/CocoaDebug/CocoaDebug/blob/58528a5f60a15839ee8c330764a6291123820bf3/Sources/Logs/_NSLogHook.m#L54) might be helpful.

**Comment by MaatheusGois** [comment]
Yessss

**Comment by DaiseiTanaka** [comment]
@heitara Thank you for your reply!

We have some questions, so please let us ask

>I believe [this](https://github.com/CocoaDebug/CocoaDebug/blob/58528a5f60a15839ee8c330764a6291123820bf3/Sources/Logs/_NSLogHook.m#L54) might be helpful.

1. Create `a custom method` to rebind NSLog for DebugSwift
2. Set `enableLogMonitoring` to `false`

Which of the above does 1 or 2 mean?

I tried option 2, but it didn't work.

>Could you please create a basic KMP project that reproduces the problem with DebugSwift library. This will speed up the development of the fix.

This verification will take some time.
Therefore, we would like to confirm whether it is correct to assume that network logs can be obtained without any problems if we use DebugSwift and KMP (Ktor) in a general way?

**Comment by heitara** [comment]
My understanding is - ktor is converted to native code from kotlin. Then DebugSwift should hook to that implementation to intercept the logs/communication.

We need a sample project to experiment with. It should be just the minimal project that is using the correct kotlin, ktor and any other version.

**Comment by DaiseiTanaka** [comment]
@heitara 
Thank you for your response!

I am currently working on a minimal KMP project and have a few questions in parallel.

>DebugSwift should hook to that implementation to intercept the logs/communication.

Does this hooking implementation already exist in DebugSwift?
If not, could you please provide the method or the relevant part of DebugSwift's implementation that would be helpful as a reference?

**Comment by heitara** [comment]
Hi! Yes, there is such implementation already for the URLSession. Alternatively, we can add an extension to Ktor to broadcast the information required to DebugSwift. We have to be sure which way would work.

**Comment by DaiseiTanaka** [comment]
@heitara 
Thank you!
It looks like @noot-programmer1 addressed the issue with [this PR](https://github.com/DebugSwift/DebugSwift/pull/121), so we'll check if it works once it's merged!
