### ISSUE TITLE
Request is always empty

### ISSUE THREAD

**Issue by YaroslavReznichenko** [DebugSwift/DebugSwift#120]
Hello. Why is request block always empty?

**Comment by MaatheusGois** [comment]
could you create a example from fork? to us simulate the problem?

**Comment by YaroslavReznichenko** [comment]
![photo_2024-12-24 20 08 05](https://github.com/user-attachments/assets/eb4bd79f-74b4-4794-a3b0-ca473d458fec)

Sorry, I have no time now to create example. Problem is that I see response json. Have no request json. It always empty. I will try to create example later)

**Comment by heitara** [comment]
Hello @YaroslavReznichenko! 

Do you use any external library or it's just URLSession?

**Comment by YaroslavReznichenko** [comment]
@heitara Alamofire

**Comment by MaatheusGois** [comment]
is the iOS 12?

**Comment by MaatheusGois** [comment]
https://github.com/DebugSwift/DebugSwift/tree/feature/post-with-alamofire

I tried recreate the issue, but here works:

<img width="472" alt="image" src="https://github.com/user-attachments/assets/7ea6f63f-65e7-47fb-8e4a-c8ebd4f82e75" />

**Comment by heitara** [comment]
@MaatheusGois he is referring to a form request. It might be upload of a file or similar.
@YaroslavReznichenko could you please be more specific?

**Comment by MaatheusGois** [comment]
is application/x-www-form-urlencoded, I tested only with json

**Comment by MaatheusGois** [comment]
working too:

<img width="472" alt="image" src="https://github.com/user-attachments/assets/ede40ac4-de0a-44bb-ba94-d0d460fc6bba" />

**Comment by YaroslavReznichenko** [comment]
I think problem was in version of Alamofire - 5.0.0 
Was updated to the latest and fixed it.

**Comment by MaatheusGois** [comment]
@heitara thanks for the support!
