### ISSUE TITLE
Unable to view API response body

### ISSUE THREAD

**Issue by yungkienpoh-prestolabs** [DebugSwift/DebugSwift#33]
Hi,
I am unable to view the response body of some APIs if the json is bigger.
If I copy and open in note, I still can't view it.

![IMG_11EF06C88249-1](https://github.com/DebugSwift/DebugSwift/assets/152136890/a1be1c1a-a6e1-465f-8254-c16e4d4b31d6)

**Comment by mrakhal** [comment]
Hi @yungkienpoh-prestolabs what version are you using?

**Comment by yungkienpoh-prestolabs** [comment]
@mrakhal Thanks for the quick reply! I am using the latest release version, 0.2.13. Is DebugSwift v3.0 alpha stable yet? I will switch to use it later then. Thanks again.

**Comment by mrakhal** [comment]
> @mrakhal Thanks for the quick reply! I am using the latest release version, 0.2.13. Is DebugSwift v3.0 alpha stable yet? I will switch to use it later then. Thanks again.

Hi @yungkienpoh-prestolabs , The v0.3.0 has now been released and is stable. Perhaps you can try upgrading to v0.3.0. Thank you 😁

**Comment by yungkienpoh-prestolabs** [comment]
Yup, I have updated to use `0.3.0-alpha.164` now, thanks a lot!
