### ISSUE TITLE
[New Feature Request]: Inspect color, size and spacing for UI components in the screen

### ISSUE THREAD

**Issue by yungkienpoh-prestolabs** [DebugSwift/DebugSwift#34]
Thanks for sharing this amazing library!

It would be even more awesome if you can add the support for debugging and inspecting the color, size and spacing of the UI components in the screen.

Here are 2 good libraries that you can get references from:
1. https://github.com/shaps80/Peek
2. https://github.com/willowtreeapps/Hyperion-iOS

**Comment by MaatheusGois** [comment]
Amazing ideia, we have a similar where you can inspecting pressing and holding the elements, and clicking in "Show more info" try it: 
https://github.com/DebugSwift/DebugSwift?tab=readme-ov-file#enhanced-hierarchy-tree-for-deeper-application-insights-beta

**Comment by yungkienpoh-prestolabs** [comment]
Thanks a lot for the fast respond, @MaatheusGois ! Yes, that is what I am looking for, thanks again!
