### ISSUE TITLE
Make Debugger Public to allow disabling Debug print messages.

### ISSUE THREAD

**Issue by yungkienpoh-prestolabs** [DebugSwift/DebugSwift#42]
Hi, is it possible to make `Debugger` `public` in `DebugSwift`, so that I can disable printing messages into the console?

<img width="449" alt="Screenshot 2024-02-18 at 10 59 14 PM" src="https://github.com/DebugSwift/DebugSwift/assets/152136890/f6f2bf64-4918-4a1d-83c0-58f8c734947f">

**Comment by MaatheusGois** [comment]
Yes, of course we can, I will resolve soon as possible :)

**Comment by yungkienpoh-prestolabs** [comment]
I have forked and created a PR to make `Debugger` `public` since we need the setting urgently. Feel free to review and merge if you think it is okay. PR link: https://github.com/DebugSwift/DebugSwift/pull/43
