### ISSUE TITLE
Add Privacy Manifest (Enforce in App Store on May 1st)

### ISSUE THREAD

**Issue by yungkienpoh-prestolabs** [DebugSwift/DebugSwift#52]
Hello -

I'm wondering what plans there are to add a Privacy Manifest?
The App Store will be enforcing this more strictly starting on May 1st.
Thanks!

https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by MaatheusGois** [comment]
Are you sending your app in prod with DebugSwift? hehehe (Normally is only to Debug), I don't know if are needed to debug the manifest :(

**Comment by yungkienpoh-prestolabs** [comment]
@MaatheusGois Yes, I only use it to debug the app in `non-production` environment. However, when I add `DebugSwift` into my `package.swift` file, it will be included in the `production` app despite we are not using it. As far as I know, there is currently no way for me to import swift package conditionally based on the build configuration: https://github.com/apple/swift-package-manager/pull/2428#issuecomment-614903476

**Comment by MaatheusGois** [comment]
![image](https://github.com/DebugSwift/DebugSwift/assets/31082311/cc1ddb55-c65a-490b-a4c2-04aa64cb3924)
@yungkienpoh-prestolabs you can try this, because is only UserDefaults and Files that DebugSwift uses :)

**Comment by yungkienpoh-prestolabs** [comment]
@MaatheusGois I have a look at the code, do I need to declare File Timestamp? I don't see the library trying to get this information in the code?

**Comment by MaatheusGois** [comment]
I think it's because of FileManager, but I'm not sure... If you can, you can use this tool to find: https://github.com/stelabouras/privacy-manifest
