### ISSUE TITLE
Last two releases are failing

### ISSUE THREAD

**Issue by heitara** [DebugSwift/DebugSwift#55]
The tag extraction step is failing.
<img width="816" alt="get latest version" src="https://github.com/DebugSwift/DebugSwift/assets/1253070/4b4e5db6-07f4-45f1-9c3d-c4a4522a4640">

@MaatheusGois I'm seeing that after the last merge the release has failed too.
 - https://github.com/DebugSwift/DebugSwift/actions/runs/8571371886

Could you please check the step that extracts the current version/tag?

**Comment by MaatheusGois** [comment]
Fixed :)
