### ISSUE TITLE
I've discovered a bug where introducing DebugSwift affects the normal functioning of Alamofire, specifically when using Alamofire to upload files. The issue arises with the `uploadProgress` method

### ISSUE THREAD

**Issue by JunkyTang** [DebugSwift/DebugSwift#56]
Hello there,

I've discovered a bug where introducing DebugSwift affects the normal functioning of Alamofire, specifically when using Alamofire to upload files. The issue arises with the `uploadProgress` method:

```swift
public func uploadProgress(queue: DispatchQueue = .main, closure: @escaping ProgressHandler) -> Self
```

This closure does not get called when DebugSwift is included. However, removing DebugSwift allows the progress closure to be called normally.

My environment details:
- iOS 17.4.1
- Xcode 15.3
- DebugSwift 0.3.1
- Alamofire 5.8.1

I would appreciate it if you could help optimize this issue. Your assistance with this problem would be greatly appreciated and beneficial to me. Thank you!

**Comment by heitara** [comment]
Hello @JunkyTang ! Could you please create a sample SwiftUI app that illustrates the problem in a separate github repo and link it here. Thanks!

**Comment by JunkyTang** [comment]
"I'm afraid it won't work because the upload service involves sensitive information, so I can only provide reference code:

```swift
session.upload(multipartFormData: { data in
    data.append(url, withName: "files")
}, to: url).uploadProgress(closure: progressHandler).responseDecodable(of: ResponseType.self) { response in
    callback(response.result)
}
```

When integrating DebugSwift via CocoaPods, `uploadProgress(closure: progressHandler)` does not trigger callbacks. Removing DebugSwift resolves the issue."

**Comment by heitara** [comment]
The problem is not a simple one - the `CustomHTTPProtocol` is not handling properly `urlSession(_ session: URLSession,
                         task: URLSessionTask,
                         didSendBodyData bytesSent: Int64,
                         totalBytesSent: Int64,
                         totalBytesExpectedToSend: Int64)`. The correct implementation should delegate this back to Alamofire. I'll keep checking for a solution. The same problem has been reported in other projects which are "capturing" the requests & responses to be able to render it.

https://github.com/pmusolino/Wormholy/issues/77

If you turn off the network reporting/viewcontroller, Alamofire will start working as expected. So, the problem is strictly related to the `URLSessionConfiguration.swizzleMethods()`.

**Comment by GraemeHarrison** [comment]
I've also noticed another issue probably related to this one: setting `URLSessionConfiguration.default.requestCachePolicy = .useProtocolCachePolicy` is ignored if `DebugSwift.setup()` is called.

**Comment by MaatheusGois** [comment]
@JunkyTang  Could you please try reproduce this issue in a PR at the DebugSwift example? :)

**Comment by heitara** [comment]
I have an example with Alamofire, based on DebugSwift example app. I'll create a PR.

**Comment by MaatheusGois** [comment]
Maybe I found one solution, not is perfect, but works fine see the @heitara PR

> I have an example with Alamofire, based on DebugSwift example app. I'll create a [PR](https://github.com/DebugSwift/DebugSwift/pull/76).

**Comment by MaatheusGois** [comment]
@JunkyTang @GraemeHarrison @heitara fix in the develop :), soo I close the create a new Release in master! Thanks for helping the project to grow!
