### ISSUE TITLE
v0.3.3: Leak Detector Crash

### ISSUE THREAD

**Issue by IsmailAhmedIsmail** [DebugSwift/DebugSwift#72]
In v 0.3.3.

after running
DebugSwift.setup()
DebugSwift.show()

I face the following crash:
"Cannot manually set translatesAutoResizingMaskIntoConstraints on a UIToolbar managed by a controller"

After adding exception breakpoint: crash is in makeScreenshot function.

**Comment by MaatheusGois** [comment]
https://github.com/DebugSwift/DebugSwift/releases/tag/0.3.4
