### ISSUE TITLE
After setup, it will cause the AMap to be unable to locate

### ISSUE THREAD

**Issue by lijianontheway** [DebugSwift/DebugSwift#79]
After setup, it will cause the AMap to be unable to locate. restored after commenting code 'CLLocationManager. swizleMethods()'. please consider adding a hidden simulated-location case in the hideFeatures.

**Comment by MaatheusGois** [comment]
Of course, I will add to disable some swizzle together with disable, or you could do it too! And open the PR 😬

**Comment by MaatheusGois** [comment]
See the issue: https://github.com/DebugSwift/DebugSwift/issues/59

**Comment by MaatheusGois** [comment]
https://github.com/DebugSwift/DebugSwift/pull/83
