### ISSUE TITLE
Multipart parameters are not rendered

### ISSUE THREAD

**Issue by heitara** [DebugSwift/DebugSwift#87]
When's multipart request is logged, the details view doesn't display its parameters.

**Comment by MaatheusGois** [comment]
Hey @heitara, how are you? Could you give me some example?

**Comment by heitara** [comment]
I'll create a mock NodeJS server. I'll create a new repo for that. I'll add the multipart example. As well the sockets example. I'll post it here once ready.
Thanks!

**Comment by heitara** [comment]
@MaatheusGois please use the following [repo](https://github.com/heitara/debugswift-strapi-server). I'll update the sample app (in my frok) to do a post request to a local server (you have to use your computer IP address). If you have any problems running the nodejs server locally please let me know.

**Comment by heitara** [comment]
@MaatheusGois have you manged to check the demo server which I've created. Any problems?

**Comment by MaatheusGois** [comment]
@heitara sorry for too long to return, I stated a new product in my company and don't have time to see this error, I will try fix now 😄

**Comment by MaatheusGois** [comment]
<img width="568" alt="image" src="https://github.com/user-attachments/assets/8b451caf-95b4-4a54-8efa-b4f15bbf4a71">
Hard to debug :>
