### ISSUE TITLE
Sharing is not implemented on the Console screen

### ISSUE THREAD

**Issue by npu3pak** [DebugSwift/DebugSwift#98]
Sharing is not implemented on the Console screen.

1. Open DebugSwift
2. Select "App" tab
3. Tap "Console"
4. Tap "Share"

Result: Nothing happens.

To fix the issue you should implement the handleShareAction() method in the AppConsoleViewModel. 
Example:
```
func handleShareAction() {
        let allData = data.joined(separator: "\n")
        FileSharingManager.generateFileAndShare(text: allData, fileName: "console")
}
```

**Comment by MaatheusGois** [comment]
Open the PR 🤣
